pipeline {
    agent any
    
    environment {
        AWS_REGION = 'us-west-2'
        AWS_CREDENTIALS = 'my-aws-credentials'
        TERRAFORM_DIR = 'TerraformDep'
    }
    
    stages {
        stage('Terraform Destroy') {
            steps {
                withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', 
                                   credentialsId: "${AWS_CREDENTIALS}",
                                   accessKeyVariable: 'AWS_ACCESS_KEY_ID', 
                                   secretKeyVariable: 'AWS_SECRET_ACCESS_KEY']]) {
                    dir("${TERRAFORM_DIR}") {
                        sh 'terraform init'
                        sh 'terraform destroy -auto-approve'
                    }
                }
            }
        }
    }
    
    post {
        failure {
            echo 'Pipeline failed! Check the logs for details.'
        }
        success {
            echo 'Resources destroyed successfully!'
        }
    }
}
